"STD char abs(char x);\n" \
"STD char2 abs(char2 x);\n" \
"STD char3 abs(char3 x);\n" \
"STD char4 abs(char4 x);\n" \
"STD short abs(short x);\n" \
"STD short2 abs(short2 x);\n" \
"STD short3 abs(short3 x);\n" \
"STD short4 abs(short4 x);\n" \
"STD int abs(int x);\n" \
"STD int2 abs(int2 x);\n" \
"STD int3 abs(int3 x);\n" \
"STD int4 abs(int4 x);\n" \
"STD half abs(half x);\n" \
"STD half2 abs(half2 x);\n" \
"STD half3 abs(half3 x);\n" \
"STD half4 abs(half4 x);\n" \
"STD float abs(float x);\n" \
"STD float2 abs(float2 x);\n" \
"STD float3 abs(float3 x);\n" \
"STD float4 abs(float4 x);\n" \
"STD float acos(float x);\n" \
"STD float acosh(float x);\n" \
"STD float asin(float x);\n" \
"STD float asinh(float x);\n" \
"STD float atan(float x);\n" \
"STD float atanh(float x);\n" \
"// TODO: add atomic functions\n" \
"STD half ceil(half x);\n" \
"STD half2 ceil(half2 x);\n" \
"STD half3 ceil(half3 x);\n" \
"STD half4 ceil(half4 x);\n" \
"STD float ceil(float x);\n" \
"STD float2 ceil(float2 x);\n" \
"STD float3 ceil(float3 x);\n" \
"STD float4 ceil(float4 x);\n" \
"STD char clamp(char x, char minVal, char maxVal);\n" \
"STD char2 clamp(char2 x, char2 minVal, char2 maxVal);\n" \
"STD char3 clamp(char3 x, char3 minVal, char3 maxVal);\n" \
"STD char4 clamp(char4 x, char4 minVal, char4 maxVal);\n" \
"STD short clamp(short x, short minVal, short maxVal);\n" \
"STD short2 clamp(short2 x, short2 minVal, short2 maxVal);\n" \
"STD short3 clamp(short3 x, short3 minVal, short3 maxVal);\n" \
"STD short4 clamp(short4 x, short4 minVal, short4 maxVal);\n" \
"STD int clamp(int x, int minVal, int maxVal);\n" \
"STD int2 clamp(int2 x, int2 minVal, int2 maxVal);\n" \
"STD int3 clamp(int3 x, int3 minVal, int3 maxVal);\n" \
"STD int4 clamp(int4 x, int4 minVal, int4 maxVal);\n" \
"STD half clamp(half x, half minVal, half maxVal);\n" \
"STD half2 clamp(half2 x, half2 minVal, half2 maxVal);\n" \
"STD half3 clamp(half3 x, half3 minVal, half3 maxVal);\n" \
"STD half4 clamp(half4 x, half4 minVal, half4 maxVal);\n" \
"STD float clamp(float x, float minVal, float maxVal);\n" \
"STD float2 clamp(float2 x, float2 minVal, float2 maxVal);\n" \
"STD float3 clamp(float3 x, float3 minVal, float3 maxVal);\n" \
"STD float4 clamp(float4 x, float4 minVal, float4 maxVal);\n" \
"STD float cos(float x);\n" \
"STD float cosh(float x);\n" \
"STD half3 cross(half3 x, half3 y);\n" \
"STD float3 cross(float3 x, float3 y);\n" \
"// TODO: add determinant function\n" \
"STD half distance(half2 x, half2 y);\n" \
"STD half distance(half3 x, half3 y);\n" \
"STD half distance(half4 x, half4 y);\n" \
"STD float distance(float2 x, float2 y);\n" \
"STD float distance(float3 x, float3 y);\n" \
"STD float distance(float4 x, float4 y);\n" \
"STD half dot(half2 x, half2 y);\n" \
"STD half dot(half3 x, half3 y);\n" \
"STD half dot(half4 x, half4 y);\n" \
"STD float dot(float2 x, float2 y);\n" \
"STD float dot(float3 x, float3 y);\n" \
"STD float dot(float4 x, float4 y);\n" \
"STD half exp(half x);\n" \
"STD half2 exp(half2 x);\n" \
"STD half3 exp(half3 x);\n" \
"STD half4 exp(half4 x);\n" \
"STD float exp(float x);\n" \
"STD float2 exp(float2 x);\n" \
"STD float3 exp(float3 x);\n" \
"STD float4 exp(float4 x);\n" \
"STD half exp2(half x);\n" \
"STD half2 exp2(half2 x);\n" \
"STD half3 exp2(half3 x);\n" \
"STD half4 exp2(half4 x);\n" \
"STD float exp2(float x);\n" \
"STD float2 exp2(float2 x);\n" \
"STD float3 exp2(float3 x);\n" \
"STD float4 exp2(float4 x);\n" \
"STD half floor(half x);\n" \
"STD half2 floor(half2 x);\n" \
"STD half3 floor(half3 x);\n" \
"STD half4 floor(half4 x);\n" \
"STD float floor(float x);\n" \
"STD float2 floor(float2 x);\n" \
"STD float3 floor(float3 x);\n" \
"STD float4 floor(float4 x);\n" \
"STD half fract(half x);\n" \
"STD half2 fract(half2 x);\n" \
"STD half3 fract(half3 x);\n" \
"STD half4 fract(half4 x);\n" \
"STD float fract(float x);\n" \
"STD float2 fract(float2 x);\n" \
"STD float3 fract(float3 x);\n" \
"STD float4 fract(float4 x);\n" \
"STD bool isinf(half x);\n" \
"STD bool2 isinf(half2 x);\n" \
"STD bool3 isinf(half3 x);\n" \
"STD bool4 isinf(half4 x);\n" \
"STD bool isinf(float x);\n" \
"STD bool2 isinf(float2 x);\n" \
"STD bool3 isinf(float3 x);\n" \
"STD bool4 isinf(float4 x);\n" \
"STD bool isnan(half x);\n" \
"STD bool2 isnan(half2 x);\n" \
"STD bool3 isnan(half3 x);\n" \
"STD bool4 isnan(half4 x);\n" \
"STD bool isnan(float x);\n" \
"STD bool2 isnan(float2 x);\n" \
"STD bool3 isnan(float3 x);\n" \
"STD bool4 isnan(float4 x);\n" \
"STD half length(half2 x);\n" \
"STD half length(half3 x);\n" \
"STD half length(half4 x);\n" \
"STD float length(float2 x);\n" \
"STD float length(float3 x);\n" \
"STD float length(float4 x);\n" \
"STD half log(half x);\n" \
"STD half2 log(half2 x);\n" \
"STD half3 log(half3 x);\n" \
"STD half4 log(half4 x);\n" \
"STD float log(float x);\n" \
"STD float2 log(float2 x);\n" \
"STD float3 log(float3 x);\n" \
"STD float4 log(float4 x);\n" \
"STD half log2(half x);\n" \
"STD half2 log2(half2 x);\n" \
"STD half3 log2(half3 x);\n" \
"STD half4 log2(half4 x);\n" \
"STD float log2(float x);\n" \
"STD float2 log2(float2 x);\n" \
"STD float3 log2(float3 x);\n" \
"STD float4 log2(float4 x);\n" \
"STD char max(char x, char y);\n" \
"STD char2 max(char2 x, char2 y);\n" \
"STD char3 max(char3 x, char3 y);\n" \
"STD char4 max(char4 x, char4 y);\n" \
"STD short max(short x, short y);\n" \
"STD short2 max(short2 x, short2 y);\n" \
"STD short3 max(short3 x, short3 y);\n" \
"STD short4 max(short4 x, short4 y);\n" \
"STD int max(int x, int y);\n" \
"STD int2 max(int2 x, int2 y);\n" \
"STD int3 max(int3 x, int3 y);\n" \
"STD int4 max(int4 x, int4 y);\n" \
"STD half max(half x, half y);\n" \
"STD half2 max(half2 x, half2 y);\n" \
"STD half3 max(half3 x, half3 y);\n" \
"STD half4 max(half4 x, half4 y);\n" \
"STD float max(float x, float y);\n" \
"STD float2 max(float2 x, float2 y);\n" \
"STD float3 max(float3 x, float3 y);\n" \
"STD float4 max(float4 x, float4 y);\n" \
"STD char min(char x, char y);\n" \
"STD char2 min(char2 x, char2 y);\n" \
"STD char3 min(char3 x, char3 y);\n" \
"STD char4 min(char4 x, char4 y);\n" \
"STD short min(short x, short y);\n" \
"STD short2 min(short2 x, short2 y);\n" \
"STD short3 min(short3 x, short3 y);\n" \
"STD short4 min(short4 x, short4 y);\n" \
"STD int min(int x, int y);\n" \
"STD int2 min(int2 x, int2 y);\n" \
"STD int3 min(int3 x, int3 y);\n" \
"STD int4 min(int4 x, int4 y);\n" \
"STD half min(half x, half y);\n" \
"STD half2 min(half2 x, half2 y);\n" \
"STD half3 min(half3 x, half3 y);\n" \
"STD half4 min(half4 x, half4 y);\n" \
"STD float min(float x, float y);\n" \
"STD float2 min(float2 x, float2 y);\n" \
"STD float3 min(float3 x, float3 y);\n" \
"STD float4 min(float4 x, float4 y);\n" \
"STD half mix(half x, half y, half a);\n" \
"STD half2 mix(half2 x, half2 y, half2 a);\n" \
"STD half3 mix(half3 x, half3 y, half3 a);\n" \
"STD half4 mix(half4 x, half4 y, half4 a);\n" \
"STD float mix(float x, float y, float a);\n" \
"STD float2 mix(float2 x, float2 y, float2 a);\n" \
"STD float3 mix(float3 x, float3 y, float3 a);\n" \
"STD float4 mix(float4 x, float4 y, float4 a);\n" \
"STD half2 normalize(half2 x);\n" \
"STD half3 normalize(half3 x);\n" \
"STD half4 normalize(half4 x);\n" \
"STD float2 normalize(float2 x);\n" \
"STD float3 normalize(float3 x);\n" \
"STD float4 normalize(float4 x);\n" \
"STD half pow(half x, half y);\n" \
"STD half2 pow(half2 x, half2 y);\n" \
"STD half3 pow(half3 x, half3 y);\n" \
"STD half4 pow(half4 x, half4 y);\n" \
"STD float pow(float x, float y);\n" \
"STD float2 pow(float2 x, float2 y);\n" \
"STD float3 pow(float3 x, float3 y);\n" \
"STD float4 pow(float4 x, float4 y);\n" \
"STD half2 reflect(half2 I, half2 N);\n" \
"STD half3 reflect(half3 I, half3 N);\n" \
"STD half4 reflect(half4 I, half4 N);\n" \
"STD float2 reflect(float2 I, float2 N);\n" \
"STD float3 reflect(float3 I, float3 N);\n" \
"STD float4 reflect(float4 I, float4 N);\n" \
"STD half2 refract(half2 I, half2 N, half eta);\n" \
"STD half3 refract(half3 I, half3 N, half eta);\n" \
"STD half4 refract(half4 I, half4 N, half eta);\n" \
"STD float2 refract(float2 I, float2 N, float eta);\n" \
"STD float3 refract(float3 I, float3 N, float eta);\n" \
"STD float4 refract(float4 I, float4 N, float eta);\n" \
"STD half round(half x);\n" \
"STD half2 round(half2 x);\n" \
"STD half3 round(half3 x);\n" \
"STD half4 round(half4 x);\n" \
"STD float round(float x);\n" \
"STD float2 round(float2 x);\n" \
"STD float3 round(float3 x);\n" \
"STD float4 round(float4 x);\n" \
"// TODO: check if integers are supported\n" \
"STD char sign(char x);\n" \
"STD char2 sign(char2 x);\n" \
"STD char3 sign(char3 x);\n" \
"STD char4 sign(char4 x);\n" \
"STD short sign(short x);\n" \
"STD short2 sign(short2 x);\n" \
"STD short3 sign(short3 x);\n" \
"STD short4 sign(short4 x);\n" \
"STD int sign(int x);\n" \
"STD int2 sign(int2 x);\n" \
"STD int3 sign(int3 x);\n" \
"STD int4 sign(int4 x);\n" \
"STD half sign(half x);\n" \
"STD half2 sign(half2 x);\n" \
"STD half3 sign(half3 x);\n" \
"STD half4 sign(half4 x);\n" \
"STD float sign(float x);\n" \
"STD float2 sign(float2 x);\n" \
"STD float3 sign(float3 x);\n" \
"STD float4 sign(float4 x);\n" \
"STD float sin(float x);\n" \
"STD float sinh(float x);\n" \
"STD half smoothstep(half edge0, half edge1, half x);\n" \
"STD half2 smoothstep(half2 edge0, half2 edge1, half2 x);\n" \
"STD half3 smoothstep(half3 edge0, half3 edge1, half3 x);\n" \
"STD half4 smoothstep(half4 edge0, half4 edge1, half4 x);\n" \
"STD float smoothstep(float edge0, float edge1, float x);\n" \
"STD float2 smoothstep(float2 edge0, float2 edge1, float2 x);\n" \
"STD float3 smoothstep(float3 edge0, float3 edge1, float3 x);\n" \
"STD float4 smoothstep(float4 edge0, float4 edge1, float4 x);\n" \
"STD half sqrt(half x);\n" \
"STD half2 sqrt(half2 x);\n" \
"STD half3 sqrt(half3 x);\n" \
"STD half4 sqrt(half4 x);\n" \
"STD float sqrt(float x);\n" \
"STD float2 sqrt(float2 x);\n" \
"STD float3 sqrt(float3 x);\n" \
"STD float4 sqrt(float4 x);\n" \
"STD half step(half edge, half x);\n" \
"STD half2 step(half2 edge, half2 x);\n" \
"STD half3 step(half3 edge, half3 x);\n" \
"STD half4 step(half4 edge, half4 x);\n" \
"STD float step(float edge, float x);\n" \
"STD float2 step(float2 edge, float2 x);\n" \
"STD float3 step(float3 edge, float3 x);\n" \
"STD float4 step(float4 edge, float4 x);\n" \
"STD float tan(float x);\n" \
"STD float tanh(float x);\n" \
"// TODO: add transpose function\n" \
"STD enum class access {\n" \
"    sample,\n" \
"    read,\n" \
"    write,\n" \
"    read_write\n" \
"};\n" \
"STD struct bias {\n" \
"    float value;\n" \
"};\n" \
"STD struct level {\n" \
"    float lod;\n" \
"};\n" \
"STD struct gradient2d {\n" \
"    float2 dPdx;\n" \
"    float2 dPdy;\n" \
"};\n" \
"STD struct min_lod_clamp {\n" \
"    float lod;\n" \
"};\n" \
"// -------- 2D --------\n" \
"// Sample\n" \
"// TODO: add more overloads\n" \
"STD char4 sample(texture2d<char> texture, sampler samplr, float2 coord, int2 offset = int2(0));\n" \
"STD short4 sample(texture2d<short> texture, sampler samplr, float2 coord, int2 offset = int2(0));\n" \
"STD int4 sample(texture2d<int> texture, sampler samplr, float2 coord, int2 offset = int2(0));\n" \
"STD half4 sample(texture2d<half> texture, sampler samplr, float2 coord, int2 offset = int2(0));\n" \
"STD float4 sample(texture2d<float> texture, sampler samplr, float2 coord, int2 offset = int2(0));\n" \
"// Read\n" \
"// TODO: add more overloads\n" \
"STD char4 read(texture2d<char> texture, ushort2 coord);\n" \
"STD short4 read(texture2d<short> texture, ushort2 coord);\n" \
"STD int4 read(texture2d<int> texture, ushort2 coord);\n" \
"STD half4 read(texture2d<half> texture, ushort2 coord);\n" \
"STD float4 read(texture2d<float> texture, ushort2 coord);\n" \
"STD char4 read(texture2d<char> texture, uint2 coord);\n" \
"STD short4 read(texture2d<short> texture, uint2 coord);\n" \
"STD int4 read(texture2d<int> texture, uint2 coord);\n" \
"STD half4 read(texture2d<half> texture, uint2 coord);\n" \
"STD float4 read(texture2d<float> texture, uint2 coord);\n" \
"// Write\n" \
"// TODO: add more overloads\n" \
"STD void write(texture2d<char> texture, char4 data, ushort2 coord);\n" \
"STD void write(texture2d<short> texture, short4 data, ushort2 coord);\n" \
"STD void write(texture2d<int> texture, int4 data, ushort2 coord);\n" \
"STD void write(texture2d<half> texture, half4 data, ushort2 coord);\n" \
"STD void write(texture2d<float> texture, float4 data, ushort2 coord);\n" \
"STD void write(texture2d<char> texture, char4 data, uint2 coord);\n" \
"STD void write(texture2d<short> texture, short4 data, uint2 coord);\n" \
"STD void write(texture2d<int> texture, int4 data, uint2 coord);\n" \
"STD void write(texture2d<half> texture, half4 data, uint2 coord);\n" \
"STD void write(texture2d<float> texture, float4 data, uint2 coord);\n" \
""